spring.application.name=mvxsprinhometask

spring.datasource.url=jdbc:postgresql://localhost:5432/hometask?currentSchema=hometask
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# HTTPS
server.port=8443

# Настройки SSL
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=superadmin
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=superadmin

spring.liquibase.contexts=dev
spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/db.changelog-master.xml


logging.level.org.liquibase=DEBUG
liquibase.validateXmlChangelogFiles=false

